# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'web.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import os
class Ui_MainWindow(object):
    cwd = os.getcwd()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(10, 70, 571, 491))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.table = QtWidgets.QTableWidget(self.frame_main)
        self.table.setGeometry(QtCore.QRect(10, 10, 551, 471))
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setGeometry(QtCore.QRect(10, 10, 571, 51))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.pushButton_out = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_out.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.pushButton_out.setObjectName("pushButton_out")
        self.pushButton_open = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_open.setGeometry(QtCore.QRect(90, 10, 71, 31))
        self.pushButton_open.setObjectName("pushButton_open")
        self.textEdit = QtWidgets.QTextEdit(self.frame_top)
        self.textEdit.setGeometry(QtCore.QRect(170, 10, 131, 31))
        self.textEdit.setObjectName("textEdit")
        self.spinBox = QtWidgets.QSpinBox(self.frame_top)
        self.spinBox.setGeometry(QtCore.QRect(400, 10, 61, 31))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.frame_top)
        self.label.setGeometry(QtCore.QRect(310, 10, 81, 31))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 10, 41, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_open.clicked.connect(Ui_MainWindow.slot_btn_chooseFile)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def slot_btn_chooseFile(self):
        fileName_choose, filetype = QFileDialog.getOpenFileName(None,"选取日志",Ui_MainWindow.cwd,"All Files (*);;logs Files (*.log)")
        #没有选择文件
        if fileName_choose == "":
            print("\n取消选择")
            return
        #选择完文件之后的操作，调用分析日志的方法
        print("\n你选择的文件为:")
        print(fileName_choose)
        print("文件筛选器类型: ", filetype)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "web日志分析工具"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "目标IP"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "时间"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "威胁类型"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "威胁描述"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "连接器"))
        self.pushButton_out.setText(_translate("MainWindow", "告警导出"))
        self.pushButton_open.setText(_translate("MainWindow", "日志导入"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">漏洞威胁值</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "搜索"))

